www/Django/ScrumMaster/Scrum/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token

app_name = "Scrum"

def_router = DefaultRouter()
def_router.register('scrumusers', views.ScrumUserViewSet)
def_router.register('scrumgoals', views.ScrumGoalViewSet)
def_router.register('scrumprojects', views.ScrumProjectViewSet)
def_router.register('scrumprojectroles', views.ScrumProjectRoleViewSet)
def_router.register(r'scrumsprint', views.SprintViewSet, base_name='scrumsprint')

'''
    path('create-user/', views.create_user, name="create_user"),
    path('init-user/', views.init_user, name="init_user"),
    path('scrum-login/', views.scrum_login, name="scrum_login"),
    path('profile/', views.profile, name="profile"),
    path('scrum-logout/', views.scrum_logout, name="scrum_logout"),
    path('add-goal/', views.add_goal, name="add_goal"),
    path('remove-goal/<int:goal_id>/', views.remove_goal, name="remove_goal"),
    path('move-goal/<int:goal_id>/<int:to_id>/', views.move_goal, name="move_goal"),
'''
    
urlpatterns = [
    url(r'api/', include(def_router.urls)),
    url(r'^api-token-auth/', obtain_jwt_token),
    path(r'create-demo/', views.createDemoUser)
]

www/Django/ScrumMaster/Scrum/templates/create_user.html
<h1>Create User</h1>
<form action="{% url 'Scrum:init_user' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username">
    <br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
    <br>
    <label for="rtpassword">Retype Password:</label>
    <input type="password" id="rtpassword" name="rtpassword">
    <br>
    <label for="full_name">Full Name:</label>
    <input type="text" id="full_name" name="full_name">
    <br>
    <label for="age">Age:</label>
    <input type="text" id="age" name="age">
    <br>
    <label for="usertype">User Type:</label>
    <select id="usertype" name="usertype">
        <option value="Owner">Owner</option>
        <option value="Admin">Admin</option>
        <option value="Developer" selected="selected">Developer</option>
        <option value="Quality Analyst">Quality Analyst</option>
    </select>
    <br>
    <input type="submit" value="Create User">
</form>

{% if messages %}
    {% for message in messages %}
        <h3>{{message}}</h3>
    {% endfor %}
{% endif %}

<a href="{% url 'login' %}">Back To Login</a>

www/Django/ScrumMaster/Scrum/templates/profile.html
<h2>Currently Logged in as {{username}} - {{role}}</h2>
<a href="{% url 'Scrum:scrum_logout' %}">Logout</a>
<br>
<h3>Your Details</h3>
<ul>
    <li>Name: {{user_info.nickname}}</li>
    <li>ID: {{user_info.id}}</li>
    <li>Age: {{user_info.age}}</li>
</ul>
<h3>Add Goal</h3>
<form action="{% url 'Scrum:add_goal' %}" method="post">
    {% csrf_token %}
    <label for="name">Name:</label>
    <input type="text" id="name" name="name">
    <br>
    <input type="submit" value="Add Goal">
</form>

{% if messages %}
    {% for message in messages %}
        <h3 style="{% if message.tags == 'success'%} color: green {% else %} color:red {% endif %};">{{message}}</h3>
    {% endfor %}
{% endif %}

<style>
    .full-box {
        text-align: center;
        border: 2px solid black;
        padding: 10px;
    }
    .top-box {
        text-align: center;
        border: 1px solid gray;
        border-top: 2px solid black;
        padding: 10px;
    }
    .reg-box {
        text-align: center;
        border: 1px solid gray;
        padding: 10px;
    }
</style>
{% if goal_list %}
    <table style="table-layout: fixed; width: 700px; word-wrap: break-word; border-collapse: collapse; border: 2px solid black;">
        <tr>
            <th colspan="6" class="full-box">Available Goal{{goal_list|pluralize}}</th>
        </tr>
        <tr>
            <th class="full-box">Created By</th>
            <th class="full-box">Weekly Goal</th>
            <th class="full-box">Daily Target</th>
            <th class="full-box">Verify</th>
            <th class="full-box">Done</th>
            <th class="full-box">Remove</th>
        </tr>
        {% for goal, goal_count in goal_list %}
            <tr>
                {% if goal_count != 0%}
                    <td rowspan="{{goal_count}}" class="full-box">{{goal.user.nickname}}</td>
                {% endif %}
                
                {% for num in nums_list %}
                    <td class="{% if goal_count != 0%} top-box {% else %} reg-box {% endif %}">
                        {% if goal.status == num %}
                            {{goal.id}}) {{goal.name}}
                        {% else %}
                            <a href="{% url 'Scrum:move_goal' goal.id num %}">-</a>
                        {% endif %}
                    </td>
                {% endfor %}
                <td class="{% if goal_count != 0%} top-box {% else %} reg-box {% endif %}">
                    <a href="{% url 'Scrum:remove_goal' goal.id %}">*</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No goals have been created.</p>
{% endif %}